### ISSUE TITLE
Unbound module Owl_opt

### ISSUE THREAD

**Issue by lodi12** [owlbarn/owl_opt#2]
I am trying to compile the example in the documentation, but I get the error:

 module O = Owl_opt.D.Adam.Make (Prms)
               ^^^^^^^^^^^^^^^^^^^
Error: Unbound module Owl_opt

I get this error with both ocaml 4.10 and 4.13.

owl-opt and owl-opt-lbfgs are installed.

where am I wrong?

Thank you for your help.

**Comment by tachukao** [comment]
maybe you're missing the ppx `preprocess`  field in the dune files?

You can see an example dune file here https://github.com/owlbarn/owl_opt/blob/master/examples/opt/dune

If this doesn't work, can you provide the code you're using to compile? thanks!

**Comment by lodi12** [comment]
Now I can compile the owl-opt example.
I still have some problem with the lbfgs example.

I build the examples with "dune build examples" but I get the error:

/usr/bin/ld: cannot find -llbfgs_fortran_stubs
/usr/bin/ld: cannot find -lbase_stubs
/usr/bin/ld: cannot find -lbase_internalhash_types_stubs
/usr/bin/ld: cannot find -lowl_stubs
collect2: error: ld returned 1 exit status

**Comment by tachukao** [comment]
Hmm these are a bit more mysterious to me. I'm not sure where the linking errors are coming from. Have you tried building the lbfgs examples individually with for example 

dune build examples/lbfgs/regression_s.exec

**Comment by lodi12** [comment]
Solved. Thank you.
